<h2>Ajouter un contact</h2>
<?=$this->form()->openTag($contactForm)?>
<div>
    <?=$this->formRow($contactForm->get('firstName'))?>
</div>
<div>
    <?=$this->formRow($contactForm->get('lastName'))?>
</div>
<div>
    <?=$this->formRow($contactForm->get('email'))?>
</div>
<div>
    <?=$this->formLabel($contactForm->get('phone'))?>
    <?=$this->formElement($contactForm->get('phone'))?>
    <span class="error">
        <?=$this->formElementErrors($contactForm->get('phone'))?>
    </span>
</div>
<div>
    <?=$this->formRow($contactForm->get('societe'))?>
</div>
<div>
    <button type="submit">Ajouter</button>
</div>
<?=$this->form()->closeTag()?>